# Generated by Django 3.0.5 on 2020-04-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='timing_closed',
            new_name='timings_closed',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='timing_open',
            new_name='timings_open',
        ),
        migrations.AlterField(
            model_name='availability',
            name='non_del_days',
            field=models.CharField(default='0000000', max_length=7, verbose_name='Non delivery days'),
        ),
        migrations.AlterField(
            model_name='onboard',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
