# Generated by Django 3.0.5 on 2020-04-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0004_auto_20200420_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupancy',
            name='id',
        ),
        migrations.AlterField(
            model_name='occupancy',
            name='lockerid',
            field=models.IntegerField(default='101', primary_key=True, serialize=False),
        ),
    ]
