# Generated by Django 3.0.5 on 2020-04-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0005_auto_20200421_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupancy',
            name='id',
            field=models.AutoField(auto_created=True, default=101, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occupancy',
            name='lockerid',
            field=models.IntegerField(default='101'),
        ),
    ]
