# Generated by Django 3.0.5 on 2020-04-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0006_auto_20200421_0058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occupancy',
            unique_together=set(),
        ),
    ]
