# Generated by Django 3.0.5 on 2020-04-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0007_auto_20200421_0104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occupancy',
            unique_together={('lockerid', 'date')},
        ),
    ]
