# Generated by Django 3.0.5 on 2020-04-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0011_auto_20200421_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupancy',
            name='lockerid',
            field=models.IntegerField(default='101'),
        ),
    ]
